export const texts = {
  zh: {
    title: 'AI 任务拆解',
    mode: '分配模式：',
    fast: '最快',
    balanced: '均衡',
    slow: '价格最低',
    inputPlaceholder: '请输入项目目标，例如：开发一个购物小程序',
    submit: '提交给 AI',
    submitting: 'AI 正在拆解中...(可能需要 1-2 分钟)',
    taskList: '任务清单：',
    task: '任务：',
    role: '角色：',
    est: '预计时间：',
    recommend: '推荐开发者：',
    none: '暂无合适开发者',
    more: '更多',
    insufficient: '时长不足者',
    moreLabel: '更多：价格过高或速度过慢',
    tooExpensive: '价格过高：',
    tooSlow: '速度过慢：',
    notEnough: '时长不足：',
    no: '无',
    others: '其他开发者：',
    select: '点击选择该开发者',
    detail: '点击查看开发者详情',
    detailInsufficient: '该开发者时长不足，仅供参考',
    totalCost: '总成本：',
    totalTime: '总耗时：',
    confirm: '确认分配',
    confirmTip: '请为每个任务选择开发者，缺人无法分配！',
    toResult: '分配结果',
    back: '返回',
    lang: 'English',
    modalInputTip: '请输入完整的项目目标，例如：开发一个购物小程序',
    modalConfirmTip: '请为每个任务选择开发者，缺人无法分配！',
    myOrders: '我的订单',
    noOrder: '暂无订单',
    orderId: '订单号',
    time: '时间',
    status: '状态',
    taskCount: '任务数',
    delete: '删除',
    close: '关闭',
    deleteConfirm: '确认删除该订单？',
    redecompose: '重新拆解任务',
    viewDetails: '查看详情',
    home: '首页',
    aiNoUnderstandError: 'AI无法理解您的需求，请提供更清晰、具体的项目目标，例如：开发一个在线购物网站，包含用户注册、商品浏览、购物车、支付功能',
    aiDataFormatError: 'AI返回的任务数据格式有误，请重新尝试。如果问题持续出现，请尝试使用更具体的项目描述。',
    aiNotTaskDataError: 'AI返回的不是任务数据，而是说明文字，请提供更明确的项目目标。',
    aiInvalidDataError: 'AI返回的任务数据无效，请尝试提供更详细的项目需求描述。',
  },
  en: {
    title: 'AI Task Decomposition',
    mode: 'Mode:',
    fast: 'Fastest',
    balanced: 'Balanced',
    slow: 'Lowest Cost',
    inputPlaceholder: 'Please enter your project goal, e.g. Develop a shopping mini-program',
    submit: 'Submit to AI',
    submitting: 'AI is decomposing... (may take 1–2 minutes)',
    taskList: 'Task List:',
    task: 'Task:',
    role: 'Role:',
    est: 'Estimated Time:',
    recommend: 'Recommended Developers:',
    none: 'No suitable developer',
    more: 'More',
    insufficient: 'Insufficient Hours',
    moreLabel: 'More: Too expensive or too slow',
    tooExpensive: 'Too expensive:',
    tooSlow: 'Too slow:',
    notEnough: 'Insufficient:',
    no: 'None',
    others: 'Other Developers:',
    select: 'Click to select this developer',
    detail: 'Click to view developer details',
    detailInsufficient: 'Insufficient hours, for reference only',
    totalCost: 'Total Cost:',
    totalTime: 'Total Duration:',
    confirm: 'Confirm Assignment',
    confirmTip: 'Please select a member for each task!',
    toResult: 'Assignment Result',
    back: 'Back',
    lang: '中文',
    modalInputTip: 'Please enter a complete project goal, e.g. Develop a shopping mini-program',
    modalConfirmTip: 'Please select a member for each task. Cannot assign if missing!',
    myOrders: 'My Orders',
    noOrder: 'No orders',
    orderId: 'Order ID',
    time: 'Time',
    status: 'Status',
    taskCount: 'Tasks',
    delete: 'Delete',
    close: 'Close',
    deleteConfirm: 'Confirm Delete?',
    redecompose: 'Re-decompose Task',
    viewDetails: 'View Details',
    home: 'Home',
    aiNoUnderstandError: 'AI cannot understand your requirements. Please provide clearer and more specific project goals, for example: Develop an online shopping website with user registration, product browsing, shopping cart, and payment functions',
    aiDataFormatError: 'The task data returned by AI is in the wrong format. Please try again. If the problem persists, try using more specific project descriptions.',
    aiNotTaskDataError: 'AI returned explanatory text instead of task data. Please provide clearer project goals.',
    aiInvalidDataError: 'The task data returned by AI is invalid. Please try providing more detailed project requirements.',
  }
} as const;


